from post.models import Post

Post(title='Salary of a SQL Data Engineer', content='Data Engineers have always had to be familiar with relational SQL databases, but with newer data analytics platforms that even offer data integration and machine learning via SQL, more and more Data Engineers are focusing on this programming language. Is this paying off?', author='Christianlauer', thumbnail='https://miro.medium.com/max/1400/1*RpZXuCqrTQu8-72qvrIjeQ.jpeg').save()
Post(title='Top 5 reasons why developers love Rust programming language', content='Rust is one of the few modern languages that has found a place in the industry where programmers are able to create code that is used by actual businesses. Let’s take a look at the things that make coding in Rust so appealing to programmers.', author='TechGig', thumbnail='https://miro.medium.com/max/828/1*NvbqYMJ1B8Y5vKBYNWNs1Q.png').save()
Post(title='My Top 8 VS Code Extensions', content='I recently gave a talk at Microsoft Ignite where I used Visual Studio Code. The most frequently asked question was what extensions are you using? So, in this post I will share my top 8 Visual Studio Code extensions.', author='Donovan Brown', thumbnail='https://miro.medium.com/max/1400/1*CnyzdBCmmCLyLvOfDVXtGg.png').save()
Post(title='Top 4 event-driven architecture patterns', content='Software systems keep evolving rapidly and the number of people using software also keeps increasing by a large margin every year. This leads to new patterns and tools being introduced to accommodate for those evolvements.', author='Mostafa Ibrahim', thumbnail='https://miro.medium.com/max/828/0*w6Hl0HfIDvy_8oUI').save()
Post(title='All About React’s Proposed New use() Hook', content='A feature proposal from the React core team is causing some buzz in the React ecosystem, drawing both excitement for its new capabilities, as well as some concerns about how it’s going to be implemented. In this post, we’ll dig into what the new feature looks like, what problem it solves, and what the concerns are being raised.', author='Jhonny G', thumbnail='https://miro.medium.com/max/828/0*n0u9Q6W4hofRPh_c').save()
Post(title='That’s why you need to understand class scopes in Python', content='Take a look at the below code and try to find out the value for each print() before checking the results. If you get them all right and completely understand why those are the right results, this article will not provide too much new information, otherwise I strongly encourage you to continue reading in order to understand the underlying concepts.', author='István Gábor Nagy', thumbnail='https://miro.medium.com/max/828/1*b2wUAxnCE7Vh4j3WTLx3SQ.png').save()
# Post(title='Blog Post 7', content='Seventh post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 8', content='Eighth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 9', content='Ninth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 10', content='Tenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 11', content='Eleventh post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 12', content='Twelfth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 13', content='Thirteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 14', content='Fourteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 15', content='Fifteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 16', content='Sixteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 17', content='Seventeenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 18', content='Eighteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 19', content='Nineteenth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()
# Post(title='Blog Post 20', content='Twentieth post content', author='Jane Doe', thumbnail='https://picsum.photos/200/300').save()


print('📚 Se han creado algunos post iniciales ')